### ISSUE TITLE
Fails when passing JS to the bot (>>)

### ISSUE THREAD

**Issue by Jayflux** [oftn-oswg/oftn-bot#48]
```
Error: spawn /home/ella/ella/lib/sandbox/sm/shovel.bin ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

Is the error I get when trying to use the Ecma features.
Node JS vs 0.12.2
Ubuntu 12.10

Tried building shovel with V8 installed ( libv8-dev (3.7.12.22-3))
But the build fails:
```
g++ shovel.cpp `pkg-config v8 --libs --cflags` -o shovel.bin -O3 -g -Wall -Wextra -pedantic -mtune=native
Package v8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `v8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'v8' found
```

**Comment by gkatsev** [comment]
Our documentation is terrible. Some should write up exactly what's needed but essentially, you want to go into each folder in [`sandox`](https://github.com/oftn/oftn-bot/tree/master/lib/sandbox/) and run `make` in each.

**Comment by ljharb** [comment]
Even better, we should just make a root `make` task that does that for you.

**Comment by Jayflux** [comment]
@gkatsev  @ljharb 
I've added some more info
it moans about Package v8 not being installed, not sure if that helps

**Comment by yorickvP** [comment]
You need to compile either the sm or v8 shovel, but you don't need both. If one of them works, that's enough.

It seems some distros don't include a v8 file for pkg-config (v8 thinks this is the distros job), so we'll have to find a fix for that.

**Comment by Jayflux** [comment]
@yorickvP  is there anything i can do as a quick fix for now just to get it working? (regarding the pkg-config issue)

**Comment by yorickvP** [comment]
Using spidermonkey instead of v8 is probably the easiest solution. You could try and replace the 'pkg-config v8 --libs --cflags' with its output, probably `-lv8 -pthread`

**Comment by Jayflux** [comment]
@yorickvP  how safe is that to use?

**Comment by yorickvP** [comment]
Should be perfectly safe.

**Comment by Jayflux** [comment]
Is it on Ubuntu's package manager or does it need to be built from source?

**Comment by Jayflux** [comment]
@yorickvP could this be solve by using https://github.com/gf3/sandbox/ instead?

**Comment by Jayflux** [comment]
This now works with the latest version of this bot (using docker)
